### ISSUE TITLE
Setting EC2 instance http_endpoint/token metadata_options breaks teleport config

### ISSUE THREAD

**Issue by Aharic** [gravitational/teleport#10962]
### Description

**What happened**:
After setting this on the proxy launch configuration:
```
metadata_options {
   http_endpoint = "enabled"
   http_tokens   = "required"
}
```

Customer's teleport configuration gets injected with raw html and mangles the customer config as seen below:

```
teleport:
  auth_token: /var/lib/teleport/token
  ca_pin: << REDACTED >>
  nodename: <?xml version="1-0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1-0 Transitional//EN"
        "http://www-w3-org/TR/xhtml1/DTD/xhtml1-transitional-dtd">
<html xmlns="http://www-w3-org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>401 - Unauthorized</title>
 </head>
 <body>
  <h1>401 - Unauthorized</h1>
 </body>
</html>
  advertise_ip: <?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>401 - Unauthorized</title>
 </head>
 <body>
  <h1>401 - Unauthorized</h1>
 </body>
</html>
  log:
    output: stderr
    severity: INFO
  data_dir: /var/lib/teleport
```

It appears that the issue is related to  the way the we're setting/using the [IMDS_TOKEN_HEADER](https://github.com/gravitational/teleport/blob/master/assets/aws/files/bin/teleport-generate-config#L67)

Customer testing showed that switching from the following:

```
IMDS_TOKEN=$(curl -m5 -sS -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 300")
IMDS_TOKEN_HEADER="-H \"X-aws-ec2-metadata-token: ${IMDS_TOKEN}\""
curl -m5 -sS "${IMDS_TOKEN_HEADER}" ${CURL_EXTRA_ARGS} [http://169.254.169.254/latest/${REQUEST_PATH}](http://169.254.169.254/latest/$%7BREQUEST_PATH%7D)
```

to the following:

```
IMDS_TOKEN=$(curl -m5 -sS -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 300")
curl -m5 -sS -H "X-aws-ec2-metadata-token: ${IMDS_TOKEN}" ${CURL_EXTRA_ARGS} [http://169.254.169.254/latest/${REQUEST_PATH}](http://169.254.169.254/latest/$%7BREQUEST_PATH%7D)
```
seems to have resolved the problem in the customer environment.

**What you expected to happen**:
Should be able to set instance metadata as specified above and not corrupt the teleport.yaml config

### Server Details
- Teleport version (run `teleport version`):

gz#4227

**Comment by fheinecke** [comment]
Confirmed and PR opened (https://github.com/gravitational/teleport/pull/13417). Thanks for the great bug report!

**Comment by fheinecke** [comment]
Close as fixed via PRs #13417, #13538, #13537, and #13704.

**Comment by r0mant** [comment]
@Aharic I'm going to reopen for now since you mentioned customer is still experiencing this issue, however please verify with them first that they're using the new version. The [PR](https://github.com/gravitational/teleport/pull/13537) basically implements the change that the ticket description says fixes the issue for them. It should be available in 9.3.9.

cc @fheinecke FYI

**Comment by webvictim** [comment]
Is this the same issue as https://github.com/gravitational/teleport/issues/14359?

**Comment by russjones** [comment]
Since we can't reproduce this anymore and it's been fixed, I am going to close this ticket. Please create another ticket if this still occurs in Teleport 10.
