### ISSUE TITLE
2.2.7 build failure due to version not being bumped

### ISSUE THREAD

**Issue by ilovezfs** [gravitational/teleport#1229]
Build log: https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/7534/version=sierra/testReport/junit/brew-test-bot/sierra/install_teleport/

Getting the failure

```
cp -rf build teleport
tar -czf teleport-v2.2.6-`go env GOOS`-`go env GOARCH`-bin.tar.gz teleport
rm -rf teleport

CREATED: teleport-v2.2.6-darwin-amd64-bin.tar.gz
==> /usr/bin/tar -xvf teleport-v2.2.7-darwin-amd64-bin.tar.gz
tar: Error opening archive: Failed to open 'teleport-v2.2.7-darwin-amd64-bin.tar.gz'
```

So it seems the version number for the tarball file name was not bumped.

**Comment by russjones** [comment]
@ilovezfs We've release Teleport 2.2.7 binaries, this should work now.

**Comment by ilovezfs** [comment]
@russjones in Homebrew, we require that formulae build from source, so this is still broken due to https://github.com/gravitational/teleport/blob/v2.2.7/Makefile#L5. I guess I will use a string replacement to fix it. Hopefully the version can actually be set correctly in the next stable release tag.
