### ISSUE TITLE
TSH command execution audit logging bugs

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#13613]
Expected behavior:
~The Session id `sid` in the command execution audit log event will be populated and match the `sid` from the corresponding session start event.~ (FIXED(

A command execution will not produce a session uploaded event as no corresponding session is available for replay in the session recording web UI

Current behavior:
~The Session id `sid` in the command execution audit log event is left blank~

A command execution produces a session uploaded event even though no corresponding session is available for replay in the session recording web UI

Bug details:
- Teleport version: 9.3.3 (cloud hosted)
- Recreation steps
Log in to a Teleport cluster, run a single `tsh ssh` command against a server, and observe the audit logging produced

**Comment by pschisa** [comment]
Another issue with audit logging of command execution here: https://github.com/gravitational/teleport/issues/13622 but tracking separate as this one was more concerning to the end user

**Comment by pschisa** [comment]
Another bug worth noting:
On my cloud cluster (v9.3.3) when I run `tsh ssh <user@server> ls`, I get a series of session.start, exec, session.data, and session.upload.

On my standalone self-hosted cluster (v9.3.6) when I run `tsh ssh <user@server> ls`, I get two execs, session.data, and session.end event.

This is mostly significant because the session.start event is not present, and thus no node labels are captured in the second (v9.3.6) exchange.

**Comment by EdwardDowling** [comment]
The missing SID in the exec audit logs has been fixed in [14061](https://github.com/gravitational/teleport/pull/14061)
@pschisa Is the preference here that no upload event actually be emitted if a previous event in that session was an exec event? Or would it be preferable that the event is emitted just the play option does not appear in the UI?

**Comment by EdwardDowling** [comment]
@pschisa Having a bit of trouble coming up with a nice way to prevent upload events for just the exec sessions. Is there a nicer way then just going back over the previous events in a session to check its not an exec session before creating the upload?

Also any luck with replicating that other issue?

**Comment by pschisa** [comment]
actually, original issue of `A command execution will not produce a session uploaded event as no corresponding session is available for replay in the session recording web UI` is still present so reopening to track that to resolution
