### ISSUE TITLE
A little report on version v2.3.1

### ISSUE THREAD

**Issue by papiveron** [gravitational/teleport#1387]
Hello,

I was recently using version `v2.3.1` on my clusters' nodes, and notice some bugs in addition to the bug reported [here](https://github.com/gravitational/teleport/issues/1381) 
I noticed that :
- `tctl users ls` command displays users empty rows for the column `Allowed to Login as`
- dynamic labels (`commands`) are not displayed in the proxy web gui

That's all what I noticed, I don't know if you can check on your side.

I got back to version `v2.2.7`

Cheers.

**Comment by kontsevoy** [comment]
@papiveron you're awesome as always, the 2nd issue has been fixed, but the 1st one I need a bit more info. can you copy&past the output please? Thanks!

**Comment by papiveron** [comment]
Hi @kontsevoy,

Let me test the latest release and provide you with information needed.

Regards,
Eugène NG

**Comment by papiveron** [comment]
Command `tctl users ls` works well for `v2.3.5`
But still can't create trusted_cluster resource as explaned here #1451 

I close this specific issue
