### ISSUE TITLE
Websocket issues after upgrading from 8.3.0

### ISSUE THREAD

**Issue by stefansedich** [gravitational/teleport#16031]
Expected behavior:

For websockets to work without issue in Chrome when using Teleport `> 8.3.0` and my sanity to return.

Current behavior:

This one is a bit weird so you might want to grab a ☕, for context we are using Teleport with cert-manager and LetsEncrypt issued certificates.

We run Jupyter behind Teleport and it utilizes websockets, when we were running Teleport 8.3.0 everything worked perfectly, as soon as we tried to upgrade to 10.1.4 we began experiencning issues where websockets were not working, I then tried varios other versions and discovered this issue was present in 8.3.12, 8.3.14, 9.3.14, 10.1.4 and 10.1.9 and the issue would go away as soon as we downgraded back to 8.3.0.

After some more investigation I found that this issue was only present with Chrome, our current workaround is to have users use FireFox or Safari where the issue does not present.

What we see is that in chrome, (and not consistently) the websocket will fail to connect with the dreaded `1006` error. Further digging into the event logs in `chrome://net-export` shows the TLS handshake failing with the following:

```
t=14301064 [st=345]      SSL_HANDSHAKE_MESSAGE_RECEIVED
                         --> bytes =
                         --> type = 20
t=14301064 [st=345]      SSL_CLIENT_CERT_REQUESTED
t=14301064 [st=345]   -SSL_CONNECT
                       --> net_error = -110 (ERR_SSL_CLIENT_AUTH_CERT_NEEDED)
```

This is the point where Chrome bails out and throws the `1006` as it appears to abort the handshake saying the server asked for client certificates (it should not have).

What is peculiar here is that things will "sometimes" work just fine if you come back to things after 15 or so minutes, but more often than not there will be issues opening the websocket, and the issue was far more difficult to replicate with Teleport 8.3.12 and 8.3.14, slightly more difficult with 9.3.14 and very easy to replicate with the 10.1.x series.

If I were to place something like [mitmproxy](https://mitmproxy.org/) in the mix and connect Chrome through the proxy, things work perfectly fine too (I suspect as mitmproxy does TLS interception, handshake and returns it's own certs), but as soon as I stop the proxy I can be back at a situation where the websocket is failing to connect again right away.

There is this Chromium issue https://bugs.chromium.org/p/chromium/issues/detail?id=1346579&q=websocket%201006&can=2 which seems somewhat related however the confusing part here is that a downgrade to 8.3.0 and everything works fine even in Chrome, but upgrading to any of the mentioned versions and the issue can soon be seen again. I would be happy to call this a Chrome bug and move on if we did not arrive back at a happy place with a simple downgrade to Teleport 8.3.0.

I have attempted to create a local k3d based replication of this issue without much success, I suspect that this is due to using self-signed certs and not LE.

Bug details:
- Teleport version: 8.3.12, 8.3.14, 9.3.14, 10.1.4, 10.1.9

**Comment by zmb3** [comment]
Thanks for the detailed report, @stefansedich - we'll try our best to dig into this soon.

**Comment by mdwn** [comment]
Hey @stefansedich, I'm currently digging into this. Are you still running into this issue? If so, I'm trying against 10.1.4 as we speak with Jupyter -- about how frequently would this occur on 10.1.4? Is there anything particular you or your users were doing in Jupyter that seemed to cause this to occur?

**Comment by stefansedich** [comment]
> Jupyter

Hi @mdwn, yes this is still happening as of 10.3.1 and is still easy for me to replicate in Chrome, we run a multi-tenant environment so to replicate this all I need to do is:

1. Open a number of tenant Jupyter instances in a number of tabs
2. Witness being unable to load the Jupyter terminal in one or more instances

Sometimes if I load one instance things might work fine, other times it wont, so it is not consistent and the only way to reliably have things working is to use FireFox.

I tried to replicate this in a local configuration but was unable to, however I was not using LE certificates in my test.

**Comment by mdwn** [comment]
@stefansedich I'm trying to replicate this in a local configuration as well with LE certs and it seems to work fine, so I'm suspecting it might not be the LE certs. Can you describe how the Jupyter instances are running? e.g. are they running in kubernetes clusters, standalone, etc.? I'd love to know how exactly they're being connected to Teleport.

**Comment by mdwn** [comment]
I've managed to reproduce this locally. It looks like, for whatever reason, the websocket requests aren't being passed through in certain instances. I'm currently trying to figure out why this would be.

**Comment by mdwn** [comment]
My reproduction of this inexplicably stopped working at some point yesterday, so @stefansedich, any information you could get me on the topology of your network would be handy.

**Comment by mdwn** [comment]
Going to use this space for fact finding.

After somehow reproducing, I got the following error messages after turning on debug logging on the proxy service:
```
Oct 22 04:24:36 ip-172-31-24-153 teleport[42380]: 2022-10-22T04:24:36Z WARN [MX:PROXY:] "\nERROR REPORT:\nOriginal Error: *net.OpError read tcp 172.31.24.153:443-&gt;170.187.164.58:61000: i/o timeout\nStack Trace:\n\t/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:398 github.com/gravitational/teleport/lib/multiplexer.detectProto\n\t/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:260 github.com/gravitational/teleport/lib/multiplexer.detect\n\t/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:222 github.com/gravitational/teleport/lib/multiplexer.(*Mux).detectAndForward\n\t/opt/go/src/runtime/asm_amd64.s:1571 runtime.goexit\nUser Message: failed to peek connection\n\tread tcp 172.31.24.153:443-&gt;170.187.164.58:61000: i/o timeout" multiplexer/multiplexer.go:225
```

And the following, perhaps corresponding bits in the app server running on a separate node:

```
Oct 22 04:24:15 ip-172-31-62-65 teleport[70359]: 2022-10-22T04:24:15Z DEBU [PROXY:AGE] Received out-of-band proxy transport request for @local-node [d03d0595-7ab2-4bd7-b84b-dca0dfa92d7a.10-1-4.teleport.mdwn.dev]. cluster:10-1-4.teleport.mdwn.dev reversetunnel/transport.go:206
```

I'm not sure if these are related to the issue, as these errors disappear despite the websocket problems persisting.

**Comment by mdwn** [comment]
@stefansedich Could you try completely closing out of Chrome and then relaunching it from the command line with `--disable-http2` and let me know if that solves the issue? It looks like it does for me.

**Comment by mdwn** [comment]
Okay, so the fix for this is in v9, v10, and v11. These haven't been released yet, but hopefully things look better after the releases with these fixes are cut.

**Comment by mdwn** [comment]
This should be fixed now. Please let me know if you have any further issues!

**Comment by ivan-tkatchev** [comment]
@stefansedich We're still seeing this issue with Teleport v11.0. Is there something we're supposed to enable in configuration to see the effects of this bugfix?
```
t=64144 [st=  0] +CONNECT_JOB  [dt=118]
t=64144 [st=  0]   +SSL_CONNECT_JOB_CONNECT  [dt=117]
t=64144 [st=  0]     +TRANSPORT_CONNECT_JOB_CONNECT  [dt=52]
t=64144 [st=  0]       +HOST_RESOLVER_MANAGER_REQUEST  [dt=1]
                        --> allow_cached_response = true
                        --> dns_query_type = 0
                        --> host = "https://dashboard.bidderstack.com"
                        --> is_speculative = false
                        --> network_anonymization_key = "null null"
                        --> secure_dns_policy = 0
t=64144 [st=  0]          HOST_RESOLVER_MANAGER_IPV6_REACHABILITY_CHECK
                          --> cached = true
                          --> ipv6_available = false
t=64144 [st=  0]          HOST_RESOLVER_MANAGER_CACHE_HIT
                          --> results = {"aliases":["dashboard.bidderstack.com"],"canonical_names":["dashboard.bidderstack.com"],"expiration":"13314966702031716","ip_endpoints":[{"endpoint_address":"188.34.155.231","endpoint_port":0}]}
t=64145 [st=  1]          HOST_RESOLVER_MANAGER_CACHE_HIT
                          --> results = {"aliases":["dashboard.bidderstack.com"],"canonical_names":["dashboard.bidderstack.com"],"expiration":"13314966702031716","ip_endpoints":[{"endpoint_address":"188.34.155.231","endpoint_port":0}]}
t=64145 [st=  1]       -HOST_RESOLVER_MANAGER_REQUEST
t=64145 [st=  1]        TRANSPORT_CONNECT_JOB_CONNECT_ATTEMPT
                        --> address = "188.34.155.231:443"
                       [ --> source_dependency = 290535 (SOCKET)](https://netlog-viewer.appspot.com/#events&s=290535)
t=64196 [st= 52]        CONNECT_JOB_SET_SOCKET
                       [ --> source_dependency = 290535 (SOCKET)](https://netlog-viewer.appspot.com/#events&s=290535)
t=64196 [st= 52]     -TRANSPORT_CONNECT_JOB_CONNECT
t=64261 [st=117]   -SSL_CONNECT_JOB_CONNECT
                    --> net_error = -110 (ERR_SSL_CLIENT_AUTH_CERT_NEEDED)
t=64262 [st=118] -CONNECT_JOB
```
