### ISSUE TITLE
Yubikey webauthn error

### ISSUE THREAD

**Issue by Jamdoog** [gravitational/teleport#17202]
Hello,

I am trying to register my user with a Yubikey for passwordless login, but every time I utilise a Yubikey (I have 4, all 4 don't work), this error comes up:

rpc error: code = Unknown desc = Error validating the authenticator response
![Screenshot 2022-10-08 at 11 38 33](https://user-images.githubusercontent.com/13838902/194703735-7dbc028a-9846-4790-ad00-22c59b2f57fa.png)

This error does not occur when trying to add the key without passwordless login.

This error also sort of occurs on CLI. No error pops up, but instead nothing happens after tapping my new key:

**jam@Jamess-MacBook-Pro ~ % tsh mfa add
Choose device type [TOTP, WEBAUTHN]: WEBAUTHN
Enter device name: KeychainC
Allow passwordless logins [YES, NO]: YES
Tap any *registered* security key
c.....
Tap your *new* security key
c....
^CERROR: context canceled**

The host of Teleport is a Debian 11 server, with the application installed via deb. 

Please let me know what other information I may provide. 

Thank you.

**Comment by Jamdoog** [comment]
Teleport.yaml snippet:

auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: <mydomain>
  proxy_listener_mode: multiplex
  authentication:
    type: local
    second_factor: on
    webauthn:
      rp_id: <mydomain>
    connector_name: passwordless

**Comment by Jamdoog** [comment]
When trying to auth on the command line. I waited 5 minutes before cancelling:



jam@Jamess-MacBook-Pro ~ % tsh login --proxy=easylogin.org:443 --debug
DEBU [CLIENT]    open /Users/jam/.tsh/easylogin.org.yaml: no such file or directory client/api.go:1056
INFO [CLIENT]    No teleport login given. defaulting to jam client/api.go:1429
INFO [CLIENT]    no host login given. defaulting to jam client/api.go:1439
INFO [CLIENT]    [KEY AGENT] Connected to the system agent: "/private/tmp/com.apple.launchd.sGZT8DQ2NP/Listeners" client/api.go:4019
DEBU [CLIENT]    not using loopback pool for remote proxy addr: easylogin.org:443 client/api.go:3974
DEBU             Attempting GET easylogin.org:443/webapi/ping webclient/webclient.go:119
DEBU [CLIENT]    not using loopback pool for remote proxy addr: easylogin.org:443 client/api.go:3974
DEBU [CLIENT]    HTTPS client init(proxyAddr=easylogin.org:443, insecure=false) client/weblogin.go:252
DEBU             Attempting platform login webauthncli/api.go:121
DEBU             Platform login failed, falling back to cross-platform error:[touch ID not available] webauthncli/api.go:127
DEBU             FIDO2: Using libfido2 for assertion webauthncli/api.go:137
DEBU             FIDO2: assertion: passwordless=true, uv=true webauthncli/fido2.go:109
DEBU             FIDO2: Info for device ioreg://4295329572: &libfido2.DeviceInfo{Versions:[]string{"U2F_V2", "FIDO_2_0", "FIDO_2_1_PRE"}, Extensions:[]string{"credProtect", "hmac-secret"}, AAGUID:[]uint8{0x2f, 0xc0, 0x57, 0x9f, 0x81, 0x13, 0x47, 0xea, 0xb1, 0x16, 0xbb, 0x5a, 0x8d, 0xb9, 0x20, 0x2a}, Options:[]libfido2.Option{libfido2.Option{Name:"rk", Value:"true"}, libfido2.Option{Name:"up", Value:"true"}, libfido2.Option{Name:"plat", Value:"false"}, libfido2.Option{Name:"clientPin", Value:"false"}, libfido2.Option{Name:"credentialMgmtPreview", Value:"true"}}, Protocols:[]uint8{0x2, 0x1}} webauthncli/fido2.go:684
DEBU             FIDO2: Device ioreg://4295329572: filtered due to lack of UV webauthncli/fido2.go:137
Tap your security key
cccc.....
^C
ERROR REPORT:
Original Error: *errors.errorString context canceled
Stack Trace:
	/private/tmp/teleport-20221001-12248-ss9bh/teleport-10.3.1/lib/auth/webauthncli/fido2.go:635 github.com/gravitational/teleport/lib/auth/webauthncli.findSuitableDevicesOrTimeout
	/private/tmp/teleport-20221001-12248-ss9bh/teleport-10.3.1/lib/auth/webauthncli/fido2.go:576 github.com/gravitational/teleport/lib/auth/webauthncli.runOnFIDO2Devices
	/private/tmp/teleport-20221001-12248-ss9bh/teleport-10.3.1/lib/auth/webauthncli/fido2.go:209 github.com/gravitational/teleport/lib/auth/webauthncli.fido2Login
	/private/tmp/teleport-20221001-12248-ss9bh/teleport-10.3.1/lib/auth/webauthncli/fido2_common.go:46 github.com/gravitational/teleport/lib/auth/webauthncli.FIDO2Login
	/private/tmp/teleport-20221001-12248-ss9bh/teleport-10.3.1/lib/auth/webauthncli/api.go:138 github.com/gravitational/teleport/lib/auth/webauthncli.crossPlatformLogin
	/private/tmp/teleport-20221001-12248-ss9bh/teleport-10.3.1/lib/auth/webauthncli/api.go:128 github.com/gravitational/teleport/lib/auth/webauthncli.Login
	/private/tmp/teleport-20221001-12248-ss9bh/teleport-10.3.1/lib/client/weblogin.go:427 github.com/gravitational/teleport/lib/client.SSHAgentPasswordlessLogin
	/private/tmp/teleport-20221001-12248-ss9bh/teleport-10.3.1/lib/client/api.go:3388 github.com/gravitational/teleport/lib/client.(*TeleportClient).pwdlessLogin
	/private/tmp/teleport-20221001-12248-ss9bh/teleport-10.3.1/lib/client/api.go:3314 github.com/gravitational/teleport/lib/client.(*TeleportClient).Login
	/private/tmp/teleport-20221001-12248-ss9bh/teleport-10.3.1/tool/tsh/tsh.go:1446 main.onLogin
	/private/tmp/teleport-20221001-12248-ss9bh/teleport-10.3.1/tool/tsh/tsh.go:994 main.Run
	/private/tmp/teleport-20221001-12248-ss9bh/teleport-10.3.1/tool/tsh/tsh.go:444 main.main
	/opt/homebrew/Cellar/go/1.19.1/libexec/src/runtime/proc.go:250 runtime.main
	/opt/homebrew/Cellar/go/1.19.1/libexec/src/runtime/asm_arm64.s:1172 runtime.goexit
User Message: context canceled

**Comment by zmb3** [comment]
Out of curiosity, what browser are you using?

**Comment by Jamdoog** [comment]
> Out of curiosity, what browser are you using?

Firefox & Safari on macOS.
Duckduckgo and safari on iOS.

**Comment by zmb3** [comment]
I have seen that since Safari 16 I can no longer register a new webauthn device in Safari. I can use a device that's already been registered just fine. I wonder if this is the same issue. Can you try another browser?

Alternatively, try going to https://webauthn.io and registering a device there. I bet that will fail too (it does for me).

**Comment by zmb3** [comment]
<img width="496" alt="image" src="https://user-images.githubusercontent.com/7527103/210656297-79f46c73-386c-4874-a686-37f10d07c3cf.png">

As a data point, I noticed that if I uncheck `require user verification` I am able to register a device in Safari.

**Comment by codingllama** [comment]
This looks similar to the situation addressed by #27221, so I would suggest making sure the Yubikey has a PIN configured before trying to use passwordless. This has been silent for a while and I think the issue was addressed, so I'll optimistically close it.

**Comment by Jamdoog** [comment]
Hello @codingllama sorry to be the bearer of bad news but this issue still persists.

I am able to add this as a passwordless device on safari, and login.

However on firefox I get the following:

_An attempt was made to use an object that is not, or is no longer, usable_

Thanks,

**Comment by codingllama** [comment]
Hey @Jamdoog. Firefox's Webauthn support has often been lacking. I'm trying to get a registration/authentication going on [webauthn.io](https://webauthn.io) to repro and it's giving me a hard time. From Teleport's PoV I don't think there's much to do.

I suggest you do the initial registration using Chrome (or a Chrome-like), and then move on to Firefox - this seems to work best for me.

> An attempt was made to use an object that is not, or is no longer, usable

I did see this once on webauthn.io, but after updating my Firefox it didn't happen anymore. I'm running Firefox 115.0.2, for reference.
