### ISSUE TITLE
`TestAgentPoolConnectionCount` flakiness

### ISSUE THREAD

**Issue by ravicious** [gravitational/teleport#22984]
Related to #22627

#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/4407492036/jobs/7721234146

#### Relevant snippet

```
    agentpool_test.go:141: 
        	Error Trace:	/__w/teleport/teleport/lib/reversetunnel/agentpool_test.go:141
        	Error:      	expected a lease to be available
        	Test:       	TestAgentPoolConnectionCount
```

**Comment by GavinFrazar** [comment]
https://github.com/gravitational/teleport/actions/runs/4449288563/jobs/7813258286

**Comment by zmb3** [comment]
So far I've determined that `pool.isAgentRequired()` is incorrectly returning true because the pool is still in its default state using the agent mesh strategy when it should be using proxy peering.

This is because the pool's update loop that runs in the background sometimes hasn't updated the tunnel strategy by the time we make the assertion.

Additionally, it looks like we attempted to reduce flakiness in #23453 by waiting for a lease:

https://github.com/gravitational/teleport/blob/268c3c8db22cc3f7bfc15bb1d1fcf092bd9281e5/lib/reversetunnel/agentpool_test.go#L134-L141

However:

1. This doesn't seem to prevent the flakiness.
2. We're never releasing the lease we acquire in the test, which may be fine but sounds incorrect.

It feels like this test is mixing external behavior and internal implementation details. It would be nice to write it in a way that only exercises the public API.

**Comment by GavinFrazar** [comment]
This test is pretty reliably causing CI failures - could we consider disabling it until it's been fixed?

**Comment by zmb3** [comment]
That sounds fine @GavinFrazar 

@dboslee mentioned that he will be able to look at it later this week, feel free to disable it until then.

**Comment by smallinsky** [comment]
Should be fixed by https://github.com/gravitational/teleport/pull/24616

**Comment by zmb3** [comment]
This is still occurring on v12: https://github.com/gravitational/teleport/actions/runs/4832207411/jobs/8610672299

@smallinsky can we get the fix backported?
