### ISSUE TITLE
[invalid payload] PDU error

### ISSUE THREAD

**Issue by Assylbek2002** [gravitational/teleport#46331]
Expected behavior:
Successfully login.

Current behavior:
![Screenshot from 2024-09-06 14-47-50](https://github.com/user-attachments/assets/a24dd18b-dba5-4f91-9547-040d9bea4d41)
when I try to connect to the machine using RDP I get this error. the machine has been added to the AD domain.

Bug details:
- Teleport version 15.0.2
- Recreation steps
Logs:
Sep 06 14:51:36 teleport.local teleport[1260353]: 2024-09-06T14:51:36+05:00 ERRO [WINDOWS_D] RDP connection failed: [invalid payload] PDU error client-ip: x.x.x.x desktop-addr:x.x.x.x desktop-name:x.x.x.x pid:1260353.1 desktop/windows_server.go:758
Sep 06 14:51:36 pam.processing.local teleport[1260353]: 2024-09-06T14:51:36+05:00 WARN [WINDOWS_D] could not record desktop recording event error:[
Sep 06 14:51:36 teleport.local teleport[1260353]: ERROR REPORT:
Sep 06 14:51:36 teleport.local teleport[1260353]: Original Error: *trace.ConnectionProblemError context canceled or timed out
Sep 06 14:51:36 teleport.local teleport[1260353]: Stack Trace:
Sep 06 14:51:36 teleport.local teleport[1260353]:         github.com/gravitational/teleport/lib/events/session_writer.go:303 github.com/gravitational/teleport/lib/events.(*SessionWriter).RecordEvent
Sep 06 14:51:36 pam.processing.local teleport[1260353]:         github.com/gravitational/teleport/lib/events/setter.go:167 github.com/gravitational/teleport/lib/events.SetupAndRecordEvent
Sep 06 14:51:36 pam.processing.local teleport[1260353]:         github.com/gravitational/teleport/lib/srv/desktop/windows_server.go:964 github.com/gravitational/teleport/lib/srv/desktop.(*WindowsService).connectRDP.(*WindowsService).makeTDPSendHandler.func5
Sep 06 14:51:36 pam.processing.local teleport[1260353]:         github.com/gravitational/teleport/lib/srv/desktop/tdp/conn.go:108 github.com/gravitational/teleport/lib/srv/desktop/tdp.(*Conn).WriteMessage
Sep 06 14:51:36 pam.processing.local teleport[1260353]:         github.com/gravitational/teleport/lib/srv/desktop/tdp/conn.go:131 github.com/gravitational/teleport/lib/srv/desktop/tdp.(*Conn).SendNotification
Sep 06 14:51:36 pam.processing.local teleport[1260353]:         github.com/gravitational/teleport/lib/srv/desktop/windows_server.go:690 github.com/gravitational/teleport/lib/srv/desktop.(*WindowsService).handleConnection.func1
Sep 06 14:51:36 pam.processing.local teleport[1260353]:         github.com/gravitational/teleport/lib/srv/desktop/windows_server.go:763 github.com/gravitational/teleport/lib/srv/desktop.(*WindowsService).handleConnection
Sep 06 14:51:36 pam.processing.local teleport[1260353]:         runtime/asm_amd64.s:1650 runtime.goexit
Sep 06 14:51:36 pam.processing.local teleport[1260353]: User Message: context canceled or timed out] pid:1260353.1 desktop/windows_server.go:965

**Comment by zmb3** [comment]
This was fixed by #43603, you just need to update.

**Comment by Assylbek2002** [comment]
@zmb3 i've updated my teleport server to version 15.4.16, but i have that error still. Can you help me please?

**Comment by zmb3** [comment]
@Assylbek2002 looks like you opened a new issue, so let's direct the conversation to that one rather than here.
