### ISSUE TITLE
Update the manual steps on the Add Application Dialog

### ISSUE THREAD

**Issue by alex-kovoy** [gravitational/teleport#4778]
We need to update the manual steps on the Add Application Dialog. Below steps are incomplete. 

![image](https://user-images.githubusercontent.com/7816406/98734032-6b17dc80-236f-11eb-8085-e038e849f709.png)

**Comment by russjones** [comment]
@benarent says this is fixed.

**Comment by benarent** [comment]
We might of closed this too early, it was still an issue on `5.0.0-beta.10`

**Comment by alex-kovoy** [comment]
it was fixed in rc2
