### ISSUE TITLE
static.go

### ISSUE THREAD

**Issue by faddat** [gravitational/teleport#619]
FATA[0000] zip: not a valid zip file                     file=web/static.go:107

This is after building teleport myself.  it works with the binaries.  Assume build directions are the issue.

**Comment by kontsevoy** [comment]
@faddat can you please provide more detail, perhaps the full output of the build? Thanks.

**Comment by kontsevoy** [comment]
@faddat nevermind, we have updated the README with instructions on how to build the web UI. 
https://github.com/gravitational/teleport/blob/master/README.md#rebuilding-web-ui

**Comment by jeremyd** [comment]
Can we get a little more information on how to create the zip that's required?  I tried npm install && npm run build, but I still get this same error when starting teleport.  Is the zip file not part of the static binary that go build produces?

**Comment by klizhentas** [comment]
@jeremyd zip file is created in `make release` target https://github.com/gravitational/teleport/blob/master/Makefile#L130

**Comment by jeremyd** [comment]
@klizhentas thank you! that worked.
