### ISSUE TITLE
File transfers in teleport UI for moderated sessions is not working in 18.4.*

### ISSUE THREAD

**Issue by oleksii-ovdak** [gravitational/teleport#62165]
**Expected behavior:**

In moderated sessions, file transfer should work after approval.

**Current behavior:**

If you specify a file name for upload or download, you will get the `lacking privileges to start unattended session` error after approval.

If you do not specify a file name for upload, you will not see this error, but the upload does not start.

If you try again, you will get:
```
disconnected
a file transfer request already exists for this session
```

**Bug details:**
- Teleport version
18.4.2
- Recreation steps

Create role for moderated session like this
```
kind: role
metadata:
  name: prod-access
spec:
  allow:
    logins:
    - root
    node_labels:
      '*': '*'
    require_session_join:
    - count: 1
      filter: contains(user.spec.roles, "auditor")
      kinds:
      - ssh
      modes:
      - moderator
      name: Require one moderator
      on_leave: ""
```
Start moderated session
Join as moderator using another account.
Specify file path (to trigger the `lacking privileges` error) or skip it.
Try to upload/download file 
Approve file transfer

- Debug logs
```
Dec 11 14:10:22 ubuntu-arm-clone teleport[18786]: 2025-12-11T14:10:22.458Z WARN [NODE]      Failed to parse subsystem request local_addr:192.168.0.229:38038 remote_addr:81.101.249.84:62944 login:panic teleport_user:teleport-user id:23 idle:1>
Dec 11 14:10:22 ubuntu-arm-clone teleport[18786]: ERROR REPORT:
Dec 11 14:10:22 ubuntu-arm-clone teleport[18786]: Original Error: *trace.AccessDeniedError lacking privileges to start unattended session
Dec 11 14:10:22 ubuntu-arm-clone teleport[18786]: Stack Trace:
Dec 11 14:10:22 ubuntu-arm-clone teleport[18786]:         github.com/gravitational/teleport/lib/srv/ctx.go:81 github.com/gravitational/teleport/lib/srv.init
Dec 11 14:10:22 ubuntu-arm-clone teleport[18786]:         runtime/proc.go:7410 runtime.doInit1
Dec 11 14:10:22 ubuntu-arm-clone teleport[18786]:         runtime/proc.go:7377 runtime.doInit
Dec 11 14:10:22 ubuntu-arm-clone teleport[18786]:         runtime/proc.go:254 runtime.main
Dec 11 14:10:22 ubuntu-arm-clone teleport[18786]:         runtime/asm_arm64.s:1223 runtime.goexit
Dec 11 14:10:22 ubuntu-arm-clone teleport[18786]: User Message: lacking privileges to start unattended session] trace_id:a5a80951e51042af15a8264ff514ef11 span_id:14f7a5eaacd68256 regular/sshserver.go:2013
Dec 11 14:10:22 ubuntu-arm-clone teleport[18786]: 2025-12-11T14:10:22.458Z ERRO [NODE]      failure handling SSH request request_type:subsystem error:[
Dec 11 14:10:22 ubuntu-arm-clone teleport[18786]: ERROR REPORT:
Dec 11 14:10:22 ubuntu-arm-clone teleport[18786]: Original Error: *trace.AccessDeniedError lacking privileges to start unattended session
Dec 11 14:10:22 ubuntu-arm-clone teleport[18786]: Stack Trace:
Dec 11 14:10:22 ubuntu-arm-clone teleport[18786]:         github.com/gravitational/teleport/lib/srv/ctx.go:81 github.com/gravitational/teleport/lib/srv.init
Dec 11 14:10:22 ubuntu-arm-clone teleport[18786]:         runtime/proc.go:7410 runtime.doInit1
Dec 11 14:10:22 ubuntu-arm-clone teleport[18786]:         runtime/proc.go:7377 runtime.doInit
Dec 11 14:10:22 ubuntu-arm-clone teleport[18786]:         runtime/proc.go:254 runtime.main
Dec 11 14:10:22 ubuntu-arm-clone teleport[18786]:         runtime/asm_arm64.s:1223 runtime.goexit
Dec 11 14:10:22 ubuntu-arm-clone teleport[18786]: User Message: lacking privileges to start unattended session] trace_id:a5a80951e51042af15a8264ff514ef11 span_id:14f7a5eaacd68256 regular/sshserver.go:2419
Dec 11 14:10:22 ubuntu-arm-clone teleport[18786]: 2025-12-11T14:10:22.458Z INFO  emitting audit event event_type:sftp fields:map[access_requests:[019b0db5-ed85-7d1a-805c-d524c6441a04] action:0 code:TS020E ei:0 error:lacking privileges to sta>
Dec 11 14:10:22 ubuntu-arm-clone teleport[18786]: 2025-12-11T14:10:22.483Z DEBU [SSH:NODE]  Closed connection remote_addr:81.101.249.84:62944 sshutils/server.go:560
```
Screen 1. Trying to download
<img width="1442" height="298" alt="Image" src="https://github.com/user-attachments/assets/a5545937-19c7-4743-8896-1fc6741cfe98" />

Screen 2. Second try = disconnect
<img width="1432" height="272" alt="Image" src="https://github.com/user-attachments/assets/502dd5cd-3c0d-4c20-a978-acbe1e9050a5" />

Screen 3. Trying to upload without file name. No results.

<img width="1441" height="341" alt="Image" src="https://github.com/user-attachments/assets/ef482c85-ad95-47b8-a53f-3ca750e3ecbe" />

Screen 4. Trying to upload with file name specified:

<img width="1442" height="448" alt="Image" src="https://github.com/user-attachments/assets/2f310f87-ca5c-419d-b2aa-57944e0a3eba" />

**Comment by atburke** [comment]
This appears to only affect 18.4. It was fixed for 18.5 in #61246.

**Comment by oleksii-ovdak** [comment]
Hi @atburke, 
Thank you for your comment.

I tested in 18.5.*
Now it works with file path specified (e.g `/home/ec2-user/test.file`)

However, uploading with "default" `~/` file path it's still failed to upload (seems to be another issue?)

Screen 1. Trying to upload to default path. Nothing happens

<img width="1448" height="367" alt="Image" src="https://github.com/user-attachments/assets/9ac75b1a-8f22-458f-9df0-546a2b6b5259" />

Screen 2. Second attempt fail with an error.

<img width="1431" height="332" alt="Image" src="https://github.com/user-attachments/assets/150394a6-6920-491e-9215-47fb8e23c362" />


Proxy version: 18.5.0
Could you please take a look on that? Should I open another issue?
Thanks!

**Comment by atburke** [comment]
This does sound like a separate issue, I'd be happy to look into it.
